### PR TITLE
[WIP] Add pptx support

### PR DESCRIPTION
**Pull request by marti4ka**
Work in Progress -> Do not merge!

see #6

### CODE REVIEW

**Comment by marti4ka** [comment]
hey @sujith3g,

this implementation works for my specific case. Could you double-check it before you merge?
I will try to add pptx tests tomorrow.

Cheers,
Martina

**Comment by marti4ka** [comment]
hey @sujith3g,

I haven't implemented the `mailto` feature yet and currently I am very occupied at work, sorry.

Cheers,
Martina

**Comment by sujith3g** [comment]
@marti4ka `mailto` feature is working without any additional code, I've created test-cases for it.

Thank you for your contribution 👍

**Comment by marti4ka** [comment]
Awesome :) thanks

**Pull request merged**
